#! /usr/bin/env python
# -*- coding: UTF-8 -*-
# -*- Mode: Python; py-indent-offset: 4 -*-
"""
Ojuba Virtual CD
Copyright © 2011, Ojuba Team <core@ojuba.org>

PyGtk+ front-end for fuseiso

        Released under terms of Waqf Public License.
        This program is free software; you can redistribute it and/or modify
        it under the terms of the latest version Waqf Public License as
        published by Ojuba.org.

        This program is distributed in the hope that it will be useful,
        but WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

        The Latest version of the license can be found on
        "http://www.ojuba.org/wiki/doku.php/رخصة_وقف_العامة"

"""
from OjubaVirtualCD import main
    
if __name__ == '__main__':
    main()

